### ISSUE TITLE
로그인을 안하고 getstoreList/getStore를 할때 jwt 인증오류 발생

### ISSUE THREAD

**Issue by 96KimBoseong** [zunbeeok/dianomi#28]
securityConfig에 예외를 경로 예외를 둬야 하는지 , 정책을 비로그인한 익명의 사용자는 getStore와 getStoreList를 할수 없게 할껀지 
의견을 여쭤 봅니다 댓글 달아 주세요

**Comment by zunbeeok** [comment]
로그인 하지 않은 회원은 주문목록을 제공하지 않습니다.
